### ISSUE TITLE
GDAX

### ISSUE THREAD

**Issue by crayse1** [ahmetertem/btcbot#12]
Can you add the GDAX market?

**Comment by ahmetertem** [comment]
Hi @crayse1 , 

Unfortunately i'm no longer maintaining this project. I'm on node.js version right now because i'm not using Windows anymore. If you want to contribute or see progress of node version see link below;
https://github.com/ahmetertem/bitcoinbot

I'll try to add all markets into this and I'm planning write a GUI via Electron.

Regards
